### ISSUE TITLE
Invalid syntax when transpiling async methods on classes

### ISSUE THREAD

**Issue by sisou** [Rich-Harris/buble#146]
There seems to be no support for `async` methods on classes:
```Javascript
class Foo {
    async bar() {
        return await something();
    }

    static async bar() {
        return await something();
    }
}
```

Bublé transpiles this to 
```Javascript
var Foo = function Foo () {};

Foo.prototype.async bar = function bar () {
    return await something();
};

Foo.async bar = function bar () {
    return await something();
};
```
which is not valid JS.

Demo here: https://buble.surge.sh/#class%20Foo%20%7B%0A%20%20%20%20async%20bar()%20%7B%0A%20%20%20%20%20%20%20%20return%20await%20something()%3B%0A%20%20%20%20%7D%0A%0A%20%20%20%20static%20async%20bar()%20%7B%0A%20%20%20%20%20%20%20%20return%20await%20something()%3B%0A%20%20%20%20%7D%0A%7D

**Comment by sisou** [comment]
Just found https://github.com/Rich-Harris/buble/pull/125. Guess it's not allowed in Bublé... how do I switch Svelte's transpiler?

**Comment by sisou** [comment]
I tested #125 and it does not fix this problem.

**Comment by frozegnome** [comment]
+1, I am running into the same issue :(

**Comment by adrianheine** [comment]
There are two issues here:

1. Bublé does not transpile async functions. That's #90 for implementing support and #113 for at least giving an error.
2. Bublé emits invalid code when encountering async functions. This issue is about methods, #109 is about arrow functions.

Both need to be fixed. Let's make this issue about invalid syntax when transpiling a class with async methods (without transpiling async functions). Head to #90 if you want to talk about implementing transpilation of async functions.
